# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPath: '$(Build.SourcesDirectory)/build'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8.0'
  inputs:
    packageType: sdk
    useGlobalJson: true

# Temporary until dotnet tool nuget-license support .NET 8.0  
# See https://github.com/tomchavakis/nuget-license/issues/200
- task: UseDotNet@2
  displayName: 'Use .NET 7.0 (Required by nuget-license)'
  inputs:
    packageType: sdk
    version: 7.0.x

- task: DotNetCoreCLI@2
  displayName: 'Restore tools'
  inputs:
    command: custom
    custom: tool
    arguments: 'restore'
    workingDirectory: '$(buildPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build binaries'
  inputs:
    command: custom
    custom: tool
    arguments: 'run dotnet-script main.csx -t build-msi'  
    workingDirectory: '$(buildPath)'
